package com.sunlines.qi.monitor.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sunlines.qi.monitor.entity.CommError;
import com.sunlines.qi.monitor.entity.Coordinate;
import com.sunlines.qi.monitor.entity.Energy;
import com.sunlines.qi.monitor.entity.GlobalParameter;
import com.sunlines.qi.monitor.entity.PowerUsageEffectiveness;
import com.sunlines.qi.monitor.entity.Temperature;
import com.sunlines.qi.monitor.entity.Warning;
import com.sunlines.qi.monitor.entity.WarningSetting;

import com.sunlines.qi.monitor.dao.CommErrorDao;
import com.sunlines.qi.monitor.dao.CoordinateDao;
import com.sunlines.qi.monitor.dao.EnergyDao;
import com.sunlines.qi.monitor.dao.GlobalParameterDao;
import com.sunlines.qi.monitor.dao.PowerUsageEffectivenessDao;
import com.sunlines.qi.monitor.dao.TemperatureDao;
import com.sunlines.qi.monitor.dao.WarningDao;
import com.sunlines.qi.monitor.dao.WarningSettingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commErrorDaoConfig;
    private final DaoConfig coordinateDaoConfig;
    private final DaoConfig energyDaoConfig;
    private final DaoConfig globalParameterDaoConfig;
    private final DaoConfig powerUsageEffectivenessDaoConfig;
    private final DaoConfig temperatureDaoConfig;
    private final DaoConfig warningDaoConfig;
    private final DaoConfig warningSettingDaoConfig;

    private final CommErrorDao commErrorDao;
    private final CoordinateDao coordinateDao;
    private final EnergyDao energyDao;
    private final GlobalParameterDao globalParameterDao;
    private final PowerUsageEffectivenessDao powerUsageEffectivenessDao;
    private final TemperatureDao temperatureDao;
    private final WarningDao warningDao;
    private final WarningSettingDao warningSettingDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commErrorDaoConfig = daoConfigMap.get(CommErrorDao.class).clone();
        commErrorDaoConfig.initIdentityScope(type);

        coordinateDaoConfig = daoConfigMap.get(CoordinateDao.class).clone();
        coordinateDaoConfig.initIdentityScope(type);

        energyDaoConfig = daoConfigMap.get(EnergyDao.class).clone();
        energyDaoConfig.initIdentityScope(type);

        globalParameterDaoConfig = daoConfigMap.get(GlobalParameterDao.class).clone();
        globalParameterDaoConfig.initIdentityScope(type);

        powerUsageEffectivenessDaoConfig = daoConfigMap.get(PowerUsageEffectivenessDao.class).clone();
        powerUsageEffectivenessDaoConfig.initIdentityScope(type);

        temperatureDaoConfig = daoConfigMap.get(TemperatureDao.class).clone();
        temperatureDaoConfig.initIdentityScope(type);

        warningDaoConfig = daoConfigMap.get(WarningDao.class).clone();
        warningDaoConfig.initIdentityScope(type);

        warningSettingDaoConfig = daoConfigMap.get(WarningSettingDao.class).clone();
        warningSettingDaoConfig.initIdentityScope(type);

        commErrorDao = new CommErrorDao(commErrorDaoConfig, this);
        coordinateDao = new CoordinateDao(coordinateDaoConfig, this);
        energyDao = new EnergyDao(energyDaoConfig, this);
        globalParameterDao = new GlobalParameterDao(globalParameterDaoConfig, this);
        powerUsageEffectivenessDao = new PowerUsageEffectivenessDao(powerUsageEffectivenessDaoConfig, this);
        temperatureDao = new TemperatureDao(temperatureDaoConfig, this);
        warningDao = new WarningDao(warningDaoConfig, this);
        warningSettingDao = new WarningSettingDao(warningSettingDaoConfig, this);

        registerDao(CommError.class, commErrorDao);
        registerDao(Coordinate.class, coordinateDao);
        registerDao(Energy.class, energyDao);
        registerDao(GlobalParameter.class, globalParameterDao);
        registerDao(PowerUsageEffectiveness.class, powerUsageEffectivenessDao);
        registerDao(Temperature.class, temperatureDao);
        registerDao(Warning.class, warningDao);
        registerDao(WarningSetting.class, warningSettingDao);
    }
    
    public void clear() {
        commErrorDaoConfig.clearIdentityScope();
        coordinateDaoConfig.clearIdentityScope();
        energyDaoConfig.clearIdentityScope();
        globalParameterDaoConfig.clearIdentityScope();
        powerUsageEffectivenessDaoConfig.clearIdentityScope();
        temperatureDaoConfig.clearIdentityScope();
        warningDaoConfig.clearIdentityScope();
        warningSettingDaoConfig.clearIdentityScope();
    }

    public CommErrorDao getCommErrorDao() {
        return commErrorDao;
    }

    public CoordinateDao getCoordinateDao() {
        return coordinateDao;
    }

    public EnergyDao getEnergyDao() {
        return energyDao;
    }

    public GlobalParameterDao getGlobalParameterDao() {
        return globalParameterDao;
    }

    public PowerUsageEffectivenessDao getPowerUsageEffectivenessDao() {
        return powerUsageEffectivenessDao;
    }

    public TemperatureDao getTemperatureDao() {
        return temperatureDao;
    }

    public WarningDao getWarningDao() {
        return warningDao;
    }

    public WarningSettingDao getWarningSettingDao() {
        return warningSettingDao;
    }

}
